spring:
  datasource:
    url: jdbc:mysql://j8d107.p.ssafy.io:4000/jtest?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password : d107

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql : debug
    org.hibernate.type : trace
