spring:
  datasource:
    url: jdbc:mysql://j8d107.p.ssafy.io:4001/jtest?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password : d107

  jpa:
    hibernate:
      ddl-auto: create #???? ???? ??? ?? ??
    properties:
      hibernate: # hibernate? ??? ??? property? ??? ? ??
        #        show_sql: true System.out? ??? sql? ?? ? ??? logger? ??? ?? ? ??? ?? ???.
        format_sql: true

logging:
  level:
    org.hibernate.sql : debug # JPA? hibernate? ???? SQL? ? ???.
    org.hibernate.type : trace